server:
  port: 9010

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/docs_manage?autoReconnect=true&useCompression=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: sql123
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 1
    maxActive: 20
    minIdle: 1
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat
  application:
    name: docs-service