server:
  port: 9000
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/docs_manage?autoReconnect=true&useCompression=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: sql123
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 1
    maxActive: 20
    minIdle: 1
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat
  mvc:
    view:
      prefix: /views/
      suffix: .html

logging:
  level:
    com.yupaits.docs.mapper: debug

app:
  name: docs-manage
  userCookie: user

jwt:
  header: auth
  expiredIn: 600
  secret: yupaits
  cookie: auth-token
