server:
  port: 11030
  context-path: /ui
  session:
    cookie:
      name: uisession

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: docs-manage
      client-secret: yupaits
      access-token-uri: http://localhost:11010/auth/oauth/token
      user-authorization-uri: http://localhost:11010/auth/oauth/authorize
    resource:
      user-info-uri: http://localhost:11010/auth/user

spring:
  thymeleaf:
    cache: false