server:
  port: 11030

security:
  oauth2:
    client:
      client-id: docs-manage
      client-secret: yupaits
      access-token-uri: http://localhost:11010/oauth/token
      user-authorization-uri: http://localhost:11010/oauth/authorize
      pre-established-redirect-uri: http://localhost:11030/auth
    resource:
      user-info-uri: http://localhost:11010/user
      prefer-token-info: false
