server:
  port: 11020

eureka:
  client:
    service-url:
      defaultZone: http://localhost:11000/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

spring:
  application:
    name: docs-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/docs-oauth2?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: sql123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    timeout: 0

security:
  oauth2:
    resource:
      id: docs-server
      user-info-uri: http://localhost:11010/auth/user
      prefer-token-info: false

# log配置
logging:
  file: /logs/docs.log
  level:
    root: warn
    com.yupaits.docs: info
